### ISSUE TITLE
xtb-python on PyPI

### ISSUE THREAD

**Issue by arosen93** [grimme-lab/xtb-python#70]
Hi @awvwgk, are there any plans to get `xtb-python` on PyPI? I'm working on a code that uses `xtb-python` and am just trying to sort out how I want to do my CI testing. It would be super convenient if I could `pip install`, but of course if that's not planned or feasible, I'll stick with conda! 

[Feel free to close at your leisure]

Cheers!
Andrew

**Comment by awvwgk** [comment]
No, I have no plans on distribution via PyPI.

There are a couple of reasons, first pip is not a reliable package manager for compiled dependencies and second I would have to bundle static and/or dynamic libraries in my extension modules and/or wheels, being not only tedious but also leading significant bloat of the package. Creating a sdist on PyPI which can actually produce the uploaded wheels will also be difficult with the available tools in the ever-changing Python build systems.

In summary, I don't see the value of distribution via PyPI given the complications in packaging, while we have a completely viable solution via conda-forge.

> It would be super convenient if I could `pip install`, but of course if that's not planned or feasible, I'll stick with conda!

I can recommend [mamba-org/provision-with-micromamba](https://github.com/marketplace/actions/provision-with-micromamba) to setup CI testing based on conda environments. I'm already transitioning my projects to this setup, since it is much more robust compared to system Python with pip.

**Comment by arosen93** [comment]
Thanks for the background and the CI tips! All very helpful :) I'll look into micromamba!

**Comment by awvwgk** [comment]
Might be worth to reevaluate the wheel building. It is not really that hard, so I might give it a shot.

**Comment by arosen93** [comment]
Beautiful. Thank you!!!
